### PR TITLE
wiringPiISR python callback functionality

### PR DESCRIPTION
**Pull request by nalajcie**
Changed the SWIG interface to retain auto-generate functionality.

Due to wiringPiISR library implementation (in separate thread), it is needed to provide thread-safe python interface. Extra checks are needed before calling python callback function (obtaining the GIL lock).

Because it's not possible to provide argument for callback function in WiringPi library, I had to create 64 different callback functions to "remember" the pin number. If such a function would be provided by WiringPi, it would be easy to simplify provided code.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Wow. That switch statement is immense. Took me a moment to figure out why it was necessary. I'm of the opinion that WiringPi should be passing two arguments to its callback functions:

* The pin which triggered the callback
* The event which triggered the callback ( RISING_EDGE, FALLING_EDGE )

It's not outside the realm of possibility for us to fork/patch WiringPi to add this functionality. Something to consider at least.

Good work otherwise, thank you. I've started on this a few times and never actually got anywhere. As always; time constraints!

**Comment by nalajcie** [comment]
Yeah, it would be cleaner if we could push some patch to WiringPi, but that would require more time (those time constraints). As for the C library i would prefer interface like:
`int wiringPiISRArg(int pin, int mode, void (*function)(void), void* arg);`
which would enable me to pass any argument I want (it can be a pin number or pointer to struct with more complicated data).

I such a function would exist, we could implement `wiringPiISR` as a special case of function `wiringPiISRArg` passing pin number (or even directly `PyObject*` python function pointer) as an argument and get rid of this ugly switch statement :).

Of course implementing `wiringPiISRArg` python wrapper could be done either by another array or (preferably) by passing struct with callback and optional args as an argument to WiringPi's `wiringPiISRArg`.

Maybe I'll try to prepare patch for WiringPi in some spare time. Unfortunately I have more pressing projects to do for now.

**Comment by nalajcie** [comment]
Hi,
I would propose to close Issues regarding non-working Interrupts (linked by me above), as this is now fixed in master.

**Comment by TominJoseph18** [comment]
Hi.
I want my python code to call a C function and receive parameters from the C code. The C code has the function to detect interrupts using the WiringPiISR function. This does not really seem to be implemented on python . I am using it to run on the odroid c2. I do not really plan on calling the python code from the C code as many libraries and dependencies cannot be supported by C.

So, I plan on using ctypes. Please help.

**Pull request merged**
